### ISSUE TITLE
Storybook GH Action Failing due to error in a Story

### ISSUE THREAD

**Issue by SeanGroff** [SelectQuoteLabs/SQForm#105]
Our Storybook GH action is failing due to an error in one of our stories.
Can someone run Storybook locally, and view the failing story in the screenshot? The error should be in the console if it doesn't appear in the browser window.

Please make this commit a `chore` as we don't need to bump the version for this. Or maybe this is an actual bug and we need to fix the component itself. In that case, do a `fix` commit.

Thanks!

<img width="1609" alt="Screen Shot 2021-03-02 at 4 44 18 PM" src="https://user-images.githubusercontent.com/4367312/109725704-2494fa80-7b77-11eb-87c2-c6abec4e8771.png">

**Comment by codyarose** [comment]
Looks like that's from my PR #103 on `SQFormTextField`.
I've found what's causing it and a fix, so I'll put together a PR
