### ISSUE TITLE
Add Testing

### ISSUE THREAD

**Issue by codyarose** [SelectQuoteLabs/SQForm#117]
Gathering information on the why's and how's for adding testing to SQForm. 

Right now our testing is basically us eyeballing components/changes to try to find any possible issues, then if we don't catch them they'll show up in the projects that use this library. Unit and integration tests can help improve confidence that everything is working as intended while we're adding new features and fixing bugs.

I think [`@testing-library/react`](https://testing-library.com/docs/react-testing-library/intro/) would be the best option and [Storybook](https://storybook.js.org/docs/react/workflows/unit-testing) seems to already be set up to work well with it. When writing tests we'll want to avoid testing implementation details whenever possible, so later on if a component needs to be refactored we likely won't need to rewrite the its tests if the end functionality stays the same.

Running the tests can be added to the CI workflow so failing tests will be caught before a PR is merged, and it can likely be added to the `commit` script to prevent failing components/tests from being committed to begin with.

**Comment by codyarose** [comment]
## Scripts
(Need to test these more to make sure I have the args setup correctly)
```json
"scripts": {
  "test": "react-scripts test",
  "test:ci": "CI=true react-scripts test"
  "test:coverage": "npm run test:ci -- --coverage"
},
```
`test` run tests in watch mode
`test:ci` run tests then exit
`test:coverage` run and create a coverage report, then exit

## CI

Example `CI.yml` jobs section with tests; I think it's as simple as this
```yaml
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test # <--
```

## Commit hook
Run tests in commit hook - pre-commit or pre-push
```json
"husky": {
  "hooks": {
    "pre-commit": "CI=true npm run test",
  }
}
```
`CI=true` will force Jest to run in CI-mode, and tests will only run once instead of launching the watcher.

## Filename conventions
According to the [CRA docs](https://create-react-app.dev/docs/running-tests/#filename-conventions):
>Jest will look for test files with any of the following popular naming conventions:
>
>Files with `.js` suffix in `__tests__` folders.
>Files with `.test.js` suffix.
>Files with `.spec.js` suffix.

My personal preference is to collocate the test files as close as possible to the component that it is testing; something like this:
```
├── src
│   ├── components
│   │   ├── ComponentA
│   │   │   ├── ComponentA.js
│   │   │   ├── ComponentA.test.js
│   │   ├── ComponentB
│   │   │   ├── ComponentB.js
│   │   │   ├── ComponentB.test.js
```

But with the current folder structure of SQForm, putting `__tests__` folders in `src/components/FOLDER_NAME/*` might be the easiest structure:
```
├── src
│   ├── components
│   │   ├── SQForm
│   │   │   ├── __tests__
│   │   │   │   ├── ComponentA.test.js
│   │   │   │   ├── ComponentB.test.js
│   │   │   ├── ComponentA.js
│   │   │   ├── ComponentB.js
│   │   ├── SQFormDialog
│   │   │   ├── __tests__
│   │   │   │   ├── ComponentC.test.js
│   │   │   ├── ComponentC.js
```

**Comment by codyarose** [comment]
## "Best practices"

We can utilize [`eslint-plugin-testing-library`](https://www.npmjs.com/package/eslint-plugin-testing-library) to enforce "best practices" and avoid common errors when writing tests. 

At a minimum, we should use the recommended and react configs:
```json
{
  "extends": [
    "plugin:testing-library/recommended",
    "plugin:testing-library/react"
  ]
}
```

There are a few [rules](https://www.npmjs.com/package/eslint-plugin-testing-library#supported-rules) not included in those configs that would be good to add as well:
```json
{
  "rules": {
    "testing-library/no-await-sync-events": "warn",
    "testing-library/no-wait-for-snapshot": "error",
    "testing-library/prefer-explicit-assert": "warn",
    "testing-library/prefer-presence-queries": "error",
    "testing-library/prefer-screen-queries": "error",
    "testing-library/prefer-wait-for": "error"
  }
}
```

**Comment by SeanGroff** [comment]
All of this looks solid. How should we start writing tests that will add value? Should we start with integration tests? Some e2e tests of the stories?

I've started with snapshot tests in the past didn't get any value from them.

**Comment by codyarose** [comment]
> All of this looks solid. How should we start writing tests that will add value? Should we start with integration tests? Some e2e tests of the stories?

 I believe we should try to follow the [Testing Trophy](https://kentcdodds.com/blog/unit-vs-integration-vs-e2e-tests) ideology, so mostly integration tests. 

Something like the "Basic Form" story would be great for an integration test because it would test how the components work in harmony. Then components that have a lot going on internally (or have a lot of props/options), perhaps `SQFormAsyncAutocomplete`, would be good candidates for unit tests (though you could argue that a test for that component in particular would qualify as an integration test).

Then if we have some hooks that are important and want to be sure that they're always functioning as intended (maybe `useForm`?) we could test those with [`react-hooks-testing-library`](https://github.com/testing-library/react-hooks-testing-library).

I haven't done much e2e testing, but, from what I understand, those may be more useful when testing an actual app, rather than a component library.

> I've started with snapshot tests in the past didn't get any value from them.

Yeah, not really a fan of snapshots. I think it's too easy to just create a snapshot without really understanding the component we're testing, and also if/when it fails it's too easy to update the snapshot without checking why it failed.

**Comment by SeanGroff** [comment]
Awesome! Let's start with an integration test of the SQForm story. Then once you've got a test or two nailed down and vetted. Let's triage issues for others to be able to assist adding tests. This is a skill we all need to build up 🚀

**Comment by codyarose** [comment]
Alright, sounds good

Do you think we should go ahead and set up the CI stuff now or add that later? If now, I'd probably start with a simple unit test to test out the workflow

**Comment by SeanGroff** [comment]
> Alright, sounds good
> 
> Do you think we should go ahead and set up the CI stuff now or add that later? If now, I'd probably start with a simple unit test to test out the workflow

Let's hold off on ci until we are comfortable with our testing implementation.

**Comment by 20BBrown14** [comment]
Me watching this thread:
![giphy (2)](https://user-images.githubusercontent.com/29528409/111808195-c586f380-88a1-11eb-88b9-a073f1789e9c.gif)
