### ISSUE TITLE
Spacing: 0 does not work for SQForm & DialogStepper Components

### ISSUE THREAD

**Issue by SeanGroff** [SelectQuoteLabs/SQForm#121]
The same fix that was applied to issue #114 needs to be applied to the SQForm and SQFormDialogStepper components

**Comment by 20BBrown14** [comment]
Correct me if I'm wrong but I think #114 handled this as well.

**Comment by SeanGroff** [comment]
@20BBrown14 Yea you're right, closing this issue. I closed and re-opened VS Code and now see the changes 🤷‍♂️
