### ISSUE TITLE
Debounce

### ISSUE THREAD

**Issue by aleerobinson** [SelectQuoteLabs/SQForm#123]
To prevent dev from having to think about things like debounce every time we use an SQForm can we implement a default of say 500ms across the board on all submits? This would help with QA complaining that the app lets them do things like the image below. Of course we can allow the user to pass in a prop to remove/override the debounce if needed.

![image](https://user-images.githubusercontent.com/43287561/110853614-70cbf300-8279-11eb-83c5-e1e893757cae.png)

**Comment by SeanGroff** [comment]
Thanks @aleerobinson 
While speaking with Adam I believe the SQForm buttons should be debounced by default with a 500ms wait.
I honestly can't think of a situation where we'd want to allow a user to click a form button rapidly so I don't even believe we need to expose a prop to disable the debounce.

With that said, we can always add this prop later as an enhancement if the need arises.

**Comment by codyarose** [comment]
@SeanGroff 
I think I have a solution for this, but wanted to clarify something before making a PR: are you saying to debounce the `onSubmit` on `SQForm` or the `onClick` on `SQFormButton`?

**Comment by SeanGroff** [comment]
> @SeanGroff 
> 
> I think I have a solution for this, but wanted to clarify something before making a PR: are you saying to debounce the `onSubmit` on `SQForm` or the `onClick` on `SQFormButton`?

Debounce any Form button to prevent a user from spam clicking a button.

**Comment by codyarose** [comment]
I'm able to debounce the form onSubmit, but `SQFormIconButton` and `SQFormButton` don't expose an onClick handler to intercept. I may be missing some knowledge concerning how `SQForm`/`Formik` handles these though..

**Comment by SeanGroff** [comment]
> I'm able to debounce the form onSubmit, but `SQFormIconButton` and `SQFormButton` don't expose an onClick handler to intercept. I may be missing some knowledge concerning how `SQForm`/`Formik` handles these though..

Yea I haven't looked but I think the `debounce` may have to occur in the scplus-shared-components library

**Comment by codyarose** [comment]
Okay it looks like `SQFormButton` uses scplus-shared-components `RoundedButton`, which does expose the onClick handler. However, we'd have to debounce the `SQForm` onSubmit and the buttons onClick - if I debounce the onClick in `SQFormButton` the form onSubmit won't be debounced because onSubmit isn't triggered by a submit button's onClick.

**Comment by codyarose** [comment]
I have this working locally with [use-debounce](https://www.npmjs.com/package/use-debounce)'s `useDebouncedCallback`, which seems to handle referential equality well
