### ISSUE TITLE
SQFormDatePicker not showing error message until we click on the datepicker again

### ISSUE THREAD

**Issue by saadurrehman-selectquote** [SelectQuoteLabs/SQForm#127]
https://www.loom.com/share/1a96b6a0ee35492b8d273dcc45f35266
SQFormDatePicker not showing error message until we click on the datepicker again, as i explained in the loom video

**Comment by caleboleary** [comment]
+1 https://www.loom.com/share/ed06b59c924447e782aa8daf072ff960
