### ISSUE TITLE
Latest GH Action for the Docs failed

### ISSUE THREAD

**Issue by SeanGroff** [SelectQuoteLabs/SQForm#134]
Figure out why the latest GH Action pipeline failed for the Docs.
This issue has likely been an issue for a while. We haven't had a docs update in months. When there's nothing to update, the job exits early.

<img width="1001" alt="Screen Shot 2021-03-16 at 4 14 57 PM" src="https://user-images.githubusercontent.com/4367312/111380892-f46b5280-8672-11eb-9d7b-40a34764990d.png">

**Comment by codyarose** [comment]
I think the error is caused by the `push --force` on a protected branch, line 219 in the screenshot.
I think there are some solutions in here: https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/38

**Comment by SeanGroff** [comment]
> I think the error is caused by the `push --force` on a protected branch, line 219 in the screenshot.
> I think there are some solutions in here: https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/38

Yep, this is exactly it. I've just been ignoring it until things around here cool down. Our docs website hasn't received much love so it's low on the bucket list currently.
