### ISSUE TITLE
SQFormDialog not accepting disabled SQFormDropdown options

### ISSUE THREAD

**Issue by laurelbean** [SelectQuoteLabs/SQForm#151]
I need to disable 1 or more items in a SQFormDropdown. When using `isDisabled: true` inside of SQForm, it works as expected. However when I try and use the same dropdown in a SQFormDialog, the options are always enabled.

Loom showing issue: https://www.loom.com/share/7487bf860fff46d0975a7464cfc04aa0

**Comment by 20BBrown14** [comment]
Interesting. Do you have the two code examples you used for the use in SQForm and the one in SQFormDialog?

**Comment by laurelbean** [comment]
The regular SQForm example:
`export const formWithDiabledDropdownItems = () => {
  const options = [
    {
      label: 'Option 1',
      value: '1',
    },
    {
      label: 'Option 2',
      value: 2,
      isDisabled: true
    },
    {
      label: 'Option 3',
      value: 3
    }
  ];

  return (
    <Card style={{padding: 16}}>
      <SQForm
        initialValues={{
          testDropdown: ''
        }}
      >
        <SQFormDropdown
          name="testDropdown"
          label="Test Disable Items"
          isRequired={true}
          displayEmpty={true}
          size={5}
        >
          {options}
        </SQFormDropdown>
      </SQForm>
    </Card>
  );
}`

The SQFormDialog example:
`export const sqFormDialog = () => (
  <>
    <h1>Click the Knobs tab below to toggle the open state of the Dialog</h1>
    <SQFormDialog
      isOpen={boolean('isOpen', false, 'Open/Close Dialog')}
      isDisabled={boolean(
        'isDisabled',
        false,
        'Toggle disabled state of Save Button'
      )}
      shouldRequireFieldUpdates={true}
      maxWidth="sm"
      onClose={action('Close button clicked')}
      onSave={handleSubmit}
      title="SQ Dialog Form"
      initialValues={MOCK_INITIAL_STATE}
      muiGridProps={{
        spacing: 2,
        alignItems: 'center'
      }}
      validationSchema={schema}
    >
      <SQFormDatePicker name="startDate" label="Start Date" />
      <SQFormDatePicker name="endDate" label="End Date" />
      <SQFormDropdown name="test" label="Test">
        {options}
      </SQFormDropdown>
    </SQFormDialog>
  </>
);`

**Comment by 20BBrown14** [comment]
This may sound silly, but:
Are you importing the correct `SQFormDropdown` from '@selectquotelabs/sqform' in your project or `../src` in storybook and __not__ `scplus-shared-components`? Disabling a specific option is a feature that was added after we split SQForm from SSC.

I'm not seeing the behavior you are when I test. And that makes sense since whether you're using SQForm or SQFormDialog shouldn't matter for disabling an option so long as you're using the correct SQFormDropdown.

**Comment by Chris-Boyle** [comment]
I am able to see the disabled state when testing it with your code above.  I imported from the src in SQForm for SQFormDropDown.
`import {SQFormDialog, SQFormDatePicker, SQFormDropdown, SQFormTextField} from '../src';`
![image](https://user-images.githubusercontent.com/20329437/112219015-74a13300-8bf2-11eb-96ea-fa22d306dab6.png)

**Comment by laurelbean** [comment]
Yes, that was the issue for my example. However, I am using the correct import in the original code where I found the issue.

**Comment by 20BBrown14** [comment]
> Yes, that was the issue for my example. However, I am using the correct import in the original code where I found the issue.

Do you have a link to a branch you're seeing this issue on?

**Comment by laurelbean** [comment]
@Chris-Boyle had me also update to the latest version of SQForm and that has solved it. Thanks all, we can close this.
