### ISSUE TITLE
SQFormDialog not showing errors on mount

### ISSUE THREAD

**Issue by abbas-ali123** [SelectQuoteLabs/SQForm#165]
I am currently working on SQFormDialog and need to display the error message when the form is open. Currently, the error is displayed when it is blurred. Also, when the field is corrected but the changes are not saved and the form is reopened it is showing the green valid icon below the text field. And again on blurring it shows the error message.
Below is the loom describing the issue:
https://www.loom.com/share/d795583fd21447f3be0921bb199698c5

**Comment by saadurrehman-selectquote** [comment]
+1 i double checked that, its happening

**Comment by saadurrehman-selectquote** [comment]
incase of loading invalid data from DB, it doesn't show error until we do onBlur, 
its happening in case of DatePicker and TextField.
