### ISSUE TITLE
SQDialogForm only body should be scrollable

### ISSUE THREAD

**Issue by 20BBrown14** [SelectQuoteLabs/SQForm#17]
I would like to see the option to have only the body be scrollable in the SQDialogForm so the header and footer buttons are always visible. You can see current functionality here: https://www.loom.com/share/dd97c034de844526afa290fbfb9adf0a
Let me know if any more details are needed.

**Comment by SeanGroff** [comment]
@20BBrown14 Looking over the Loom video can you try adjusting the `maxWidth` prop of the Modal?
Ideally, modals should never scroll vertically. It's a UI smell.

Can you try making the maxWidth larger to accommodate for the large body of text and report back? I would try `xl`

Here are the `maxWidth` available options

```
  /** Determine the max-width of the dialog. The dialog width grows with the size of the screen. Set to false to disable maxWidth. */
  maxWidth: PropTypes.oneOf(['xs', 'sm', 'md', 'lg', 'xl', false]),
```

**Comment by 20BBrown14** [comment]
I'm not so sure that'll solve the issue. If we have a long block of text that's wrapping and causing the modal to need to scroll this could be an issue. But if I have a lot of questions (specific to this instance) with larger or smaller label text this won't solve the issue. See: https://www.loom.com/share/006d03958fbe41d08b2de2755be1e144

**Comment by Chris-Boyle** [comment]
@20BBrown14 have you tried wrapping your content body in a div with a defined height?

**Comment by 20BBrown14** [comment]
@Chris-Boyle good call. What ultimately worked as setting a max-height to allow for dynamic sizes of the dialog depending on the size of the dialog body.

**Comment by codyarose** [comment]
Sounds like some `position: sticky` on `<DialogTitle>` and `<DialogActions>` could solve this. Here's a quick demo just using inline styles: https://www.loom.com/share/5c5888520b8149ae99e9c763cc950513
