### ISSUE TITLE
SQFormDatePicker doesn't close in a SQFormDialog

### ISSUE THREAD

**Issue by laurelbean** [SelectQuoteLabs/SQForm#170]
Loom video of issue: https://www.loom.com/share/a524c32875a949cb8ef56d14c3eceaff

The calendar doesn't close if you click outside when the date picker is in a Dialog.

**Comment by saadurrehman-selectquote** [comment]
Yes i am also facing this issue

**Comment by codyarose** [comment]
> Without looking too closely I would guess we're getting bamboozled by z-index. The overlay that closes the datepicker might be behind the dialog so clicking the dialog doesn't close the date picker.

Yeah I'm guessing that might be the culprit, but the date picker doesn't seem to have an extra overlay. If it's not the z-index it could have something to do with both of them using portals or the dialog hijacking the focus

**Comment by hvilander** [comment]
Did we find a solution? I am also facing this issue.

**Comment by codyarose** [comment]
> Did we find a solution? I am also facing this issue. 

I've been looking into it, but haven't been able to find a working solution so far. 

This problem _has_ been mentioned elsewhere, so I think it may be a Mui thing and not necessarily just an error on our part.

**Comment by hvilander** [comment]
As I dug in a bit deeper I actually have this issue on an SQForm inside of a scplus-shared-components' Dialog. So that may make my situation a bit different.

**Comment by hvilander** [comment]
I have another case of this, but in my second case it really is in a SQFormDialog.

**Comment by hvilander** [comment]
I saw that our own @codyarose got a response to this very question [here](https://github.com/mui-org/material-ui/issues/25135#issuecomment-812483780) I will be taking a look at that suggestion today.
