### ISSUE TITLE
Create Typescript Declaration file (*.d.ts) 

### ISSUE THREAD

**Issue by caleboleary** [SelectQuoteLabs/SQForm#177]
Let's try to figure out how to expose all of our proptypes so that typescript projects can use these components with accurate typing. Same as https://github.com/SelectQuoteLabs/SQHooks/issues/6 in SQHooks

**Comment by codyarose** [comment]
The package [react-to-typescript-definitions](https://github.com/KnisterPeter/react-to-typescript-definitions) seems like a good option. I created a script to try it out, this is the output when fed `SQFormDropdown`:

```ts
declare module "SQFormDropdown" {
  import * as React from "react";

  export interface SQFormDropdownChildren {
    label?: string;
    value?: string | number;
    isDisabled?: boolean;
  }

  export type SQFormDropdownSize =
    | "auto"
    | 1
    | 2
    | 3
    | 4
    | 5
    | 6
    | 7
    | 8
    | 9
    | 10
    | 11
    | 12;

  export interface SQFormDropdownProps {
    /**
     * Dropdown options to select from
     */
    children?: SQFormDropdownChildren[];
    /**
     * Whether to display empty option - - in options
     */
    displayEmpty?: boolean;
    /**
     * Disabled property to disable the input if true
     */
    isDisabled?: boolean;
    /**
     * Required property used to highlight input and label if not fulfilled
     */
    isRequired?: boolean;
    /**
     * Label text
     */
    label: string;
    /**
     * Name identifier of the input field
     */
    name: string;
    /**
     * Custom onBlur event callback
     */
    onBlur?: (...args: any[]) => any;
    /**
     * Custom onChange event callback
     */
    onChange?: (...args: any[]) => any;
    /**
     * Size of the input given full-width is 12.
     */
    size?: SQFormDropdownSize;
    /**
     * Any valid prop for material ui select child component - https://material-ui.com/api/select/#props
     */
    muiFieldProps?: Object;
  }

  const SQFormDropdown: React.FC<SQFormDropdownProps>;

  export default SQFormDropdown;
}

```

Not 100% sure I got the options right, but it looks pretty good

**Comment by caleboleary** [comment]
@codyarose thanks for sending that along. I did some fiddling with this today and was able to get it to pump out .d.ts for each of the components in SQForm (just a node script you could call with `npm run` command hitting a js file). The two big problems for me now are:

1. I don't actually know what this needs to look like in its final form. One giant index.d.ts? It doesn't want to let me have more than 1 module per file. A parallel ExampleComponent.d.ts next to each component file? I'm struggling to find very helpful docs for adding declarations to a JS codebase. 

2. Once we get the .d.ts file(s) generated, how do we make sure they get bundled with the package? I found https://www.npmjs.com/package/rollup-plugin-dts which might be useful or might not be.

**Comment by codyarose** [comment]
Yeah, I'm not sure about those either. I think in SQHooks it generates an index as well as files for each component/hook.

**Comment by SeanGroff** [comment]
Closing this issue in favor of issue #244 
After speaking with Caleb, it's very challenging and not well documented how to create a TS declaration file generated from Prop Types.
