### ISSUE TITLE
SQFormAutocomplete has an empty option in the list of options

### ISSUE THREAD

**Issue by Chris-Boyle** [SelectQuoteLabs/SQForm#179]
A recent change to SQFormAutocomplete fixed a warning about the component being controlled/uncontrolled by adding an empty option.  This solved the warning but now gives us an empty option at the bottom of the dropdown.  This may not be desirable to most consumers so we should look into how we can omit the empty option and still not throw warnings about the component state going from controlled/uncontrolled.

introduced by: https://github.com/SelectQuoteLabs/SQForm/pull/146/files

![image](https://user-images.githubusercontent.com/20329437/113421238-5d034080-9390-11eb-8625-ec272d035fdf.png)

**Comment by 20BBrown14** [comment]
This one's on me haha. For context here is an explanation of why the empty option is _there_ but obviously we should try to avoid this if at all possible

https://github.com/SelectQuoteLabs/SQForm/pull/146#discussion_r599705601
