### ISSUE TITLE
SQFormDatePickerWithCalendarInputOnly doesn't close in SQFormDialog

### ISSUE THREAD

**Issue by saadurrehman-selectquote** [SelectQuoteLabs/SQForm#185]
SQFormDatePickerWithCalendarInputOnly doesn't close in SQFormDialog

https://www.loom.com/share/8d9bc4ba8a0b470c938fa62d30d49543

**Comment by hvilander** [comment]
This should be resolved with v4.5.1. What version are you on?

**Comment by saadurrehman-selectquote** [comment]
i checked , this issue exist for the SQFormDatePickerWithCalendarInputOnly

**Comment by hvilander** [comment]
You are right, I did not update that component.

**Comment by codyarose** [comment]
That component uses SQFormDatePicker, so it should work, but there are probably conflicts with SQFormDatePickerWithCalendarOnly also handling the calendar open/close state

**Comment by saadurrehman-selectquote** [comment]
yup other datePicker working but not this one https://www.loom.com/share/e5c2b3c025d24e1fa3be4df5746866ba

**Comment by codyarose** [comment]
Fixed by #192
