### ISSUE TITLE
SQFormTextField - max characters / helper text

### ISSUE THREAD

**Issue by lucas-homer** [SelectQuoteLabs/SQForm#19]
We need the ability to set a max number of characters an input allows, so that a user gets that info up front via helper text, but the input also bails out of the `onChange` event when it reaches the max number of characters set via a consumer prop. In this kind of situation, we would probably want to give the user the max char info via helper text and _not_ via Yup validation because the input should limit the characters itself, which would be preferred to not limiting the input but telling via error text that the user's exceeded the max chars value. In these kinds of cases, we'd probably limit the error text (and thus, Yup schema) to whether it's a required field.

**Comment by codyarose** [comment]
@lucas-homer I think I could pick this up - just worked on improving basically the same exact thing that exists on the senior CRM TextField component. In that instance the character counter, if a max characters amount is specified, is added directly to the label, e.g., `Subject : 0/30`. The amount is passed to the inputs `maxLength` attribute via `inputProps` to prevent the user from typing beyond the limit.
