### ISSUE TITLE
SqformDropdown Cannot read property 'persist' of undefined

### ISSUE THREAD

**Issue by shahzaib-haider1** [SelectQuoteLabs/SQForm#193]
We are getting `persist' of undefined error if we disable the dropdown after changing the dropdown option.
here is a loom video
https://www.loom.com/share/83ba436e8a5949eaad402bc02175ef39

**Comment by codyarose** [comment]
I've tried recreating what you have set up in `SQForm.stories.js`, but I'm not getting the error. Whenever I select 'Arizona' the field simply disables as expected.

https://www.loom.com/share/f38a725a4ed9435db50d4260907a213f
