### ISSUE TITLE
Validation errors are showing for filled required fields

### ISSUE THREAD

**Issue by shahzaib-haider1** [SelectQuoteLabs/SQForm#199]
If we revert the changes for required fields and after re-opening the popup we are getting validation errors for required fields.
Here is a loom video
https://www.loom.com/share/d49d98b062e3489882aaf017e063c984

**Comment by hvilander** [comment]
Tried to reproduce was an able
@shahzaib-haider1 if you have a few minutes could you try again. I think this may have been resolved. 

https://www.loom.com/share/adeae85b613a48ad9fa4557ca6525e76
