### ISSUE TITLE
SQFormDropdown doesn't align with other fields

### ISSUE THREAD

**Issue by hvilander** [SelectQuoteLabs/SQForm#212]
![image](https://user-images.githubusercontent.com/2816261/114565523-f3f4b600-9c36-11eb-85f7-5b0b89fe7238.png)
If you look closely in this image you can see the line under the "State" Dropdown is slightly lower than the TextFields before it. 

I have built this into a story on an example branch. I will link to below.

**Comment by hvilander** [comment]
This story shows the issue https://github.com/SelectQuoteLabs/SQForm/blob/example-for-issue-212/stories/SQForm.stories.js#L811

**Comment by codyarose** [comment]
The text inputs have the class `.MuiInputBase-input`, which has 
```css
height: 1.1876em;
```

Then the select has the same class as well as `.MuiSelect-selectMenu`, which includes the styles
```css
height: 1.6667rem;
min-height: 1.1876em;
```

To make them line up you could probably just override the height on that select class with `height: 0;` to make the `min-height` take over
