### ISSUE TITLE
Masked values should not be masked when submitted

### ISSUE THREAD

**Issue by Chris-Boyle** [SelectQuoteLabs/SQForm#224]
I ran into a scenario where I would like to use a masked field for the phone number value but when the form submits the phone number it is in masked format and not just the digits.  I think the masked part should be a UI thing and the value sent in submission should not be masked.

**current behavior**: value is still masked when sent to the DB "(321) 123-1232"
**proposed behavior**: value is only masked in the UI and is just numeric when submitted like "3211231232"

Here is what a screen shot of the masked value being submitted in our Storybook
http://localhost:6006/?path=/story/forms-sqform--basic-form-with-masked-fields
![image](https://user-images.githubusercontent.com/20329437/116725707-edd93600-a9a7-11eb-8036-33aeed3de833.png)

Current workaround is to strip the non-numeric values when handling the submit
```
  const handleSubmit = (values) => {
    const phoneNumber = values.phoneNumber.replace(/[^\d]/g, '');
    saveForm(phoneNumber );
  };
  ```

**Comment by hvilander** [comment]
I have also seen this in the wild. I meant to post this a while back. I have done a bit of digging into this.

Do we only want to strip the masked characters for phone numbers or all masks?

**Comment by Chris-Boyle** [comment]
@hvilander I think form most we would want to remove the mask. The ones I think need the mask removed when submitting are phone, zip, currency, percent, and ssn.  I think leaving the email mask and date mask is fine.
