### ISSUE TITLE
Console warning links to non-existent common issues page

### ISSUE THREAD

**Issue by Chris-Boyle** [SelectQuoteLabs/SQForm#252]
Our intelligent SQForm project helps users when they do something wrong.  The issue is that it is telling users to go to a page that does not exist https://selectquotelabs.github.io/SQForm/docs/common_issues
```
nextjs  | https://next-auth.js.org/warnings#jwt_auto_generated_signing_key
nextjs  | SQForm: The initialValue you provided to SQForm for the SQFormDropdown (name='Shopping for a policy for a mobile manufactured home?') component was undefined. This can cause warnings and unexpected behavior. More information: https://selectquotelabs.github.io/SQForm/docs/common_issues
```

**Comment by 20BBrown14** [comment]
The page does exist (https://github.com/SelectQuoteLabs/SQForm/blob/master/SQFormDocs/docs/common_issues.mdx) but the docs github action fails so it never got deployed. see: https://github.com/SelectQuoteLabs/SQForm/issues/134

**Comment by Chris-Boyle** [comment]
Thanks @20BBrown14 .  I will close this issue now that we have the link.
