### ISSUE TITLE
SQFormCheckbox not updating value when SQForm.initialValues changes

### ISSUE THREAD

**Issue by gdoohen1** [SelectQuoteLabs/SQForm#256]
[Here is a loom](https://www.loom.com/share/f2c668ab776b4c299a94629c173e2316) showcasing my issue but essentially I have an `<SQForm/>` for which its `initialValues` prop is being updated when the selection in a table changes. I do have `enableReinitialize={true}` and I have some `<SQFormTextField/>`s in the form that are updating their values when the form gets updated as a sanity check that the form is actually being updated. In the loom I show a console error I am getting from the `<SQFormCheckbox/>`es but here is an image of the error:
![Screen Shot 2021-05-19 at 2 52 25 PM](https://user-images.githubusercontent.com/80288816/119016097-6a7b8680-b94e-11eb-84f7-58fd751b4c72.png)

**Comment by lucas-homer** [comment]
After pulling down and investigating, we identified an implementation issue outside of SQForm/SQFormCheckbox related to `React.cloneElement`, which was solved by avoiding `cloneElement` altogether :) Going to close this issue as I think we isolated the issue, and I don't believe there's a bug in SQForm
