### ISSUE TITLE
add Prop to change the color of submit button from teal to green

### ISSUE THREAD

**Issue by saadurrehman-selectquote** [SelectQuoteLabs/SQForm#288]
![image](https://user-images.githubusercontent.com/76514364/119855745-9c32b580-bf2b-11eb-9a4b-037e3b20df5f.png)
i was implementing the breaking change of shared-component on senior and I found this issue that button color is not green, and I couldn't find any prop to change it, 
![image](https://user-images.githubusercontent.com/76514364/119855884-bcfb0b00-bf2b-11eb-9eff-9dcbdfaff08e.png)

**Comment by SeanGroff** [comment]
@saadurrehman-selectquote Thanks for taking on this issue. I'm going to assign this to you and mark this issue as "In progress".

**Comment by codyarose** [comment]
This should be solved by #291
