### ISSUE TITLE
The latest changelog is not published to the deployed Storybook/Chromatic site

### ISSUE THREAD

**Issue by Chris-Boyle** [SelectQuoteLabs/SQForm#300]
With each merge of code we should be publishing a new version of our library.  This new version is put into the Changelog file and when the code is deployed the new changelog file is shown in Storybook.  

Currently when we deploy a new version of the library the Changelog is still showing the previous Version.  

We should see this in Storybook
![image](https://user-images.githubusercontent.com/20329437/120867323-4ecfcd00-c557-11eb-9e8b-46ed0490dcae.png)

Instead we see
![image](https://user-images.githubusercontent.com/20329437/120867348-5a22f880-c557-11eb-9137-8e243e63195c.png)

**Comment by laurelbean** [comment]
Not sure exactly what changed but I checked and it seems to be working now. Closing.
