### ISSUE TITLE
Downgrade react-scripts to 3.4.3 to emit eslint warnings

### ISSUE THREAD

**Issue by 20BBrown14** [SelectQuoteLabs/SQForm#304]
Currently in SQForm if there is an eslint warning (no-unused-vars, for instance) the whole compilation and build comes to a grinding halt. This is _really_ annoying while developing. There is an issue with react-scripts 4.x.x that causes this. Downgrading to react-scripts 3.4.3 fixes the issue.

This shouldn't affect our code quality because when we run `npm run commit` eslint is still run and the commit fails if there are eslint warnings.

**Comment by laurelbean** [comment]
Looks like this might be resolved. Open a new issue if this is still occurring.
