### ISSUE TITLE
SQFormMultiSelect tooltip disable prop

### ISSUE THREAD

**Issue by jamesgriffith9519** [SelectQuoteLabs/SQForm#313]
Component: SQFormMultiSelect : https://github.com/SelectQuoteLabs/SQForm/blob/master/src/components/SQForm/SQFormMultiSelect.js

I ran into a scenario when using the SQFormMultiSelect and specifically it's the on-hover tooltip that is displayed. When hovering over the input it displays the selected items and it does work, however, after your list of items grows the tooltip gets very large in size. I've attached a quick loom to demonstrate this here: https://www.loom.com/share/18e789906b58496c901926ecf581c66d

I don't think we would have giant lists selected too often but I know at times we may and the tooltip will likely get in the way for users, if we had a prop that would/could disable tooltip that might be preferred for SQFormMultiSelect instances that may have many options checked.

**Comment by lucas-homer** [comment]
I'm curious why we even have a tooltip for this in the first place. Seems like overkill considering we show the selected items (though truncated) in a list in the input.

**Comment by lucas-homer** [comment]
We faced this issue again :) I wish I could either:
1. disable tooltip, or
2. feed the component my own tooltip text, be it static or dynamic. In this case, I can provide informative text rather than listing potentially hundreds of items in a not-very-informative and yet absolute unit of a tooltip.

**Comment by caleboleary** [comment]
> We faced this issue again :) I wish I could either:
> 
> 1. disable tooltip, or
> 2. feed the component my own tooltip text, be it static or dynamic. In this case, I can provide informative text rather than listing potentially hundreds of items in a not-very-informative and yet absolute unit of a tooltip.

I'd like both of these options. Doing a state select right now, would love to show the state abbrevs in the tooltip instead of their full names, but want full names in the select.
