### ISSUE TITLE
Fix failing tests on master

### ISSUE THREAD

**Issue by 20BBrown14** [SelectQuoteLabs/SQForm#320]
There are ~20 failing tests on master at the time of this writing. Some of them definitely seem related to the addition of SQFormMultiValue. This issue should be used to fix them.

is there a particular reason we don't have the tests in the CI pipeline?

**Comment by codyarose** [comment]
There's an issue to add it to the pipeline #167. We were holding off on adding that until we were more comfortable with implementing tests ([ref](https://github.com/SelectQuoteLabs/SQForm/issues/117#issuecomment-802933768)) - I think it's probably time to get that running though

**Comment by SeanGroff** [comment]
> There's an issue to add it to the pipeline #167. We were holding off on adding that until we were more comfortable with implementing tests ([ref](https://github.com/SelectQuoteLabs/SQForm/issues/117#issuecomment-802933768)) - I think it's probably time to get that running though

Approved.
I'd also consider this a high priority issue.

The main question is do we want this as part of our `pre-commit` to avoid pushing up code that doesn't pass our tests?

The other option is to omit it from our `pre-commit` and get used to running these tests in Jest watchmode while developing like we should be doing now anyway.

Then ensure tests are passing in our `ci` GitHub Action

**Comment by codyarose** [comment]
Pretty sure we had a slack discussion about this a while back - I think the conclusion may have been no pre-commit, run jest watch locally, double check with ci

**Comment by 20BBrown14** [comment]
> > There's an issue to add it to the pipeline #167. We were holding off on adding that until we were more comfortable with implementing tests ([ref](https://github.com/SelectQuoteLabs/SQForm/issues/117#issuecomment-802933768)) - I think it's probably time to get that running though
> 
> Approved.
> I'd also consider this a high priority issue.
> 
> The main question is do we want this as part of our `pre-commit` to avoid pushing up code that doesn't pass our tests?
> 
> The other option is to omit it from our `pre-commit` and get used to running these tests in Jest watchmode while developing like we should be doing now anyway.
> 
> Then ensure tests are passing in our `ci` GitHub Action

That's always the ten million cpu cycle question.

My opinion is that we get into the habit of running in watch mode, and checking tests before we commit. However, I don't think it should be a part of the pre-commit script as that'll just slow down committing. If all i did was change a typo for some PR feedback it seems silly to have to run all the tests.

Plus the Github Action that'll run these tests is so much more valuable for our testing and code quality than running tests locally. So if our github action fails I consider that a win, as it prevented us from merging a bug and/or failing tests to master.

**Comment by codyarose** [comment]
I would think eventually everyone would get used to running tests locally when they get tired of ci failing because they didn't run tests locally
