### ISSUE TITLE
Convert SQFormTextarea to TS

### ISSUE THREAD

**Issue by shoaibhassan** [SelectQuoteLabs/SQForm#341]

**Comment by abbas-ali123** [comment]
I think this issue is already been resolved in https://github.com/SelectQuoteLabs/SQForm/pull/325

**Comment by shoaibhassan** [comment]
@abbas-ali123 Yeah just noticed that from the list.
Now this issue will be about the conversion of SQFormTextarea to TS

**Comment by codyarose** [comment]
#354
