### ISSUE TITLE
Migrate `SQFormDatePicker.js` to TS

### ISSUE THREAD

**Issue by shoaibhassan** [SelectQuoteLabs/SQForm#369]

**Comment by hvilander** [comment]
Hey I think this is my fault, but this duplicates #357.
How far into work are you on this?

**Comment by shoaibhassan** [comment]
@hvilander Yeah, I have completed the work and preparing for PR. I think #357 is not linked and being tracked that is why in the list it was showing as a TODO task.

**Comment by hvilander** [comment]
Quite right, the linking of the issue was where I erred. I will remove my duplicate once you post your PR.

**Comment by hvilander** [comment]
Also you should probably assign this issue #369 to yourself.
