### ISSUE TITLE
Need submit button to be enable while state change from value to empty string

### ISSUE THREAD

**Issue by shahzaib-haider1** [SelectQuoteLabs/SQForm#37]
We are facing an issue, the submit button gets disabled when we change the field value to null.

here is a loom video
https://www.loom.com/share/fa971642974f422b8f64284ac678e86e

**Comment by SeanGroff** [comment]
@shahzaib-haider1 Thank you for submitting this issue.
I'll look into accounting the dirty state for the submit button
