### ISSUE TITLE
SQFormGuidedWorkflow component has padding issue when we update the version of **scplus-shared-components** in SQForm

### ISSUE THREAD

**Issue by shahidmanzoorzekiexperts** [SelectQuoteLabs/SQForm#374]
When we updated the version of **scplus-shared-components** in SQForm then it causes a Padding issue with SQFormGuidedWorkflow component. 
https://www.loom.com/share/66e8fc9316124bc4aed2c0e3fa27a2c2

**Comment by gdoohen1** [comment]
Closed by PR https://github.com/SelectQuoteLabs/SQForm/pull/375
