### ISSUE TITLE
SQFormAutoComplete resets form state on blur

### ISSUE THREAD

**Issue by chris-boyle-sq** [SelectQuoteLabs/SQForm#38]
After selecting a value in the autocomplete field the rest of the fields that were validated are reset.  This causes required fields that were filled in to now show as needing to be touched again to be valid.   This is affecting all consumers of the SQFormAutoComplete component (dialog forms and forms). 

Steps to reproduce
Update the SQForm basic form example to have `isRequired={true}` on every field. 
Fill out the fields and when you get to the autocomplete field take not of all the validated fields with the green check mark.  
After leaving the auto complete field all fields that were validated will have their state reset to their initial state value.

Loom: https://www.loom.com/share/d7f51ceb423b45ed802851ca693f64af

**Comment by chris-boyle-sq** [comment]
I am going to start digging into this since it is currently blocking me.

**Comment by SeanGroff** [comment]
I've noticed this as well. Certainly a bug.
