### ISSUE TITLE
Remove hasUpdate Util and fast-deep-equal dependency

### ISSUE THREAD

**Issue by gdoohen1** [SelectQuoteLabs/SQForm#386]
> [Question] Does anyone know if `hasFormBeenUpdated` is ever different from `dirty`? The [Formik docs](https://formik.org/docs/api/formik#dirty-boolean) for `dirty` say that it is calculated by deep comparing `initialValues` and `values` but it looks like this is also the implementation of `hasUpdated` so not sure if these two ways of calculating basically the same thing are different/necessary.

Forgot I wrote this util function awhile back. 
I'm pretty sure we can delete that `util` function which would also allow us to remove the fast-deep-equal dependency. I don't believe it's used anywhere else.

_Originally posted by @SeanGroff in https://github.com/SelectQuoteLabs/SQForm/pull/385#discussion_r681974351_

**Comment by SeanGroff** [comment]
This issue was resolved with PR https://github.com/SelectQuoteLabs/SQForm/pull/388
