### ISSUE TITLE
SQFormMaskedTextField MASK phone removes the number 1 from the fourth digit

### ISSUE THREAD

**Issue by Chris-Boyle** [SelectQuoteLabs/SQForm#392]
Steps to reproduce:
1. Open a form using the phone number MASK https://5f4431386ea00a00220d495c-tnusnrsxxl.chromatic.com/?path=/story/forms-sqform--basic-form-with-masked-fields
2. Add a phone number to the phone field like 816 419 2158
3.a. in the middle of the number remove the 4
- The number 1 after the 4 will also be removed

Scenario 2
1. Open a form using the phone number MASK https://5f4431386ea00a00220d495c-tnusnrsxxl.chromatic.com/?path=/story/forms-sqform--basic-form-with-masked-fields
2. Start adding a phone number with the number 1 as the fourth digit
- The field will not allow 1 to be the fourth digit

Loom: https://www.loom.com/share/d0f691bf72114a438e0392fb283cf5a8

**Comment by hvilander** [comment]
Did a bit of research. The phone mask is defined here:
```
export const MASKS = {
  phone: [
    '(',
    /[02-9]/,
    /\d/,
    /\d/,
    ')',
    ' ',
    /[02-9]/,
    /\d/,
    /\d/,
    '-',
    /\d/,
    /\d/,
    /\d/,
    /\d/
  ],
  ```
  
  It the regex for the mask is ignoring the one by design for both the 4th and 1st positions. Do we want to change the phone mask? I am going to go look into phone number standards, but I suspect this is by design.
  
  Demo: https://www.loom.com/share/b2925d94deaf41c593d2d36a14d96b86
  
  Perhaps we want to cover scenario 1 better? Example: if I type (387) 413-1324 BUT the correct local code is 313. That would be very annoying to have the 1 go away as well.

**Comment by hvilander** [comment]
https://en.wikipedia.org/wiki/North_American_Numbering_Plan
Looks like the area code (NPA) and central office code (positions 4-6) are limited to 2-9. 
![image](https://user-images.githubusercontent.com/2816261/128249381-d79ce163-a962-4735-a09f-785df39b790b.png)

**Comment by hvilander** [comment]
Maybe this is more of a concern for validation than masking. As it will be difficult to handle the first case. Deleting an number causing the 4th position to become a one. z

Thoughts?

**Comment by Chris-Boyle** [comment]
I would lean towards just enforcing number and not requiring certain numbers to not be allowed. I can see International numbers being scrutinized differently so we should just relax our rules.

**Comment by hvilander** [comment]
If we do have to support international numbers we would have to do a lot more than drop this requirement.
For example the UK has variable length numbers
![image](https://user-images.githubusercontent.com/2816261/128256004-e51c901b-20ed-4a61-a649-43e4170d4096.png)

**Comment by Chris-Boyle** [comment]
I would still lean towards relaxing our rules so the component doesn’t do anything unexpected. Just allow the user to enter the phone number wrong rather than “fix” the number for them and not allow a 1 in certain spots.

**Comment by codyarose** [comment]
> I would still lean towards relaxing our rules so the component doesn’t do anything unexpected. Just allow the user to enter the phone number wrong rather than “fix” the number for them and not allow a 1 in certain spots. 

Yeah, that makes sense. 
If we want to prevent invalid phone numbers I imagine a validation schema could be added by the consumer that checks for invalid numbers in certain positions
