### ISSUE TITLE
Migrate to MUIv5

### ISSUE THREAD

**Issue by SeanGroff** [SelectQuoteLabs/SQForm#447]
Base Branch: **issue-447/MUI5_migration**

Example Component(s): **LoadingIcon** & **LoadingSpinner**

Migration Guides: 
  - Blog Post: https://mui.com/blog/mui-core-v5/#v4-migration
  - General Upgrade Guide: https://mui.com/material-ui/migration/migration-v4/
  - Styles Guide: https://mui.com/material-ui/migration/v5-style-changes/
  - Components Guide: https://mui.com/material-ui/migration/v5-component-changes/
  - Date/Time Pickers Guide: https://mui.com/x/react-date-pickers/getting-started/
  
**MUIv5 Migration**

- [x] #701
- [x] Upgrade to v10 of SSC once its upgraded to MUIv5
- [x] Loading Icon (Can we use one from SSC?)
- [x] LoadingSpinner (Can we use one from SSC?)
- [x] #704
- [x] #705
- [x] #723 
- [x] #706
- [x] #716 
- [x] #719
- [x] #721 
- [x] #745 
- [x] #749 
- [x] #748 
- [x] #751 
- [x] #717
- [x] #725 
- [x] #729 
- [x] #730
- [x] #732 
- [x] #733
- [x] #724 
- [x] #735 
- [x] #737 
- [x] #738 
- [x] #739 
- [x] #713 
- [x] #754 
- [x] #756
- [x] #708
- [x] #710 
- [x] #742 
- [x] #761
- [x] #764 
- [x] #766 
- [x] #768 
- [x] #769 
- [x] #770 
- [x] #773 
- [x] #772 
- [x] #776 
- [x] #777 
- [x] #779 
- [x] #784 
- [x] #796
- [x] #792
- [x] #790
- [x] #788 
- [x] #800
- [x] #794

**Comment by codyarose** [comment]
I'm guessing this should happen before the TS migration is merged since it seems like there are some improved types. And should scplus be upgraded to v5 before this as well since we have it as a dependency?

**Comment by SeanGroff** [comment]
> I'm guessing this should happen before the TS migration is merged since it seems like there are some improved types. And should scplus be upgraded to v5 before this as well since we have it as a dependency?

I need to perform discovery on the effects of migrating to v5.
Doing this prior to the TS Migration for better types would be the ideal path!

**Comment by SeanGroff** [comment]
We should be able to follow the same work and approach we're performing on SSC

**Comment by 20BBrown14** [comment]
SOmeone added this ` Look into spacing issues on certain components (Ex: SQFormHelperText spacing on SQFormDialog Validation story)`. Whoever did that, could you expand on it and let us know what exactly you're seeing?

**Comment by aharpt** [comment]
> SOmeone added this ` Look into spacing issues on certain components (Ex: SQFormHelperText spacing on SQFormDialog Validation story)`. Whoever did that, could you expand on it and let us know what exactly you're seeing?

@20BBrown14 I added this.  Here is a loom outlining what I am seeing. https://www.loom.com/share/01cb73296a2a4a92993191514f1dc2a2
