### ISSUE TITLE
SQFormScrollableCard -- if `isHeaderDisabled` is set to true, `title` should not be required

### ISSUE THREAD

**Issue by lucas-homer** [SelectQuoteLabs/SQForm#448]
At the moment, `title` prop is required, but if `isHeaderDisabled` is set to `true` we don't do anything with it, so let's not make it required.

https://www.loom.com/share/8b30454e4beb4555945ab083482ce29d

**Comment by aharpt** [comment]
@laurelbean @20BBrown14 @hvilander Took a look at this issue, and it appears that this work is already done: https://www.loom.com/share/f2fe4aad3cae4fed9523d1d8d02f6a47.

**Comment by laurelbean** [comment]
So from what I'm seeing now, `title` is not required. However, I think want it to be required unless you choose `isHeaderDisabled`. So I think we could still improve things by implementing something similar to what you did with the Accordion component.
https://bitbucket.org/SelectQuote/scplus-shared-components/pull-requests/282#Lsrc/components/Accordion/Accordion.tsxT5

**Comment by aharpt** [comment]
@laurelbean Sounds good, I'll take a look at implementing that.
