### ISSUE TITLE
 Green Success Indicator on the Fields is missing.

### ISSUE THREAD

**Issue by shahidmanzoorzekiexperts** [SelectQuoteLabs/SQForm#480]
When the conditions on a Field are initially Required, and then Fulfilled, and the form is SAVED (making it a Clean Form, again, with Saved and Valid Values),  Green Success Indicator on the Fields is missing.

![bug](https://user-images.githubusercontent.com/80986065/146599234-0662bb93-f89f-411d-b9dc-51715853d5d4.png)

**Comment by SeanGroff** [comment]
Please include the version of SQForm and a reproduction demo.

**Comment by shahidmanzoorzekiexperts** [comment]
Loom: [https://www.loom.com/share/8d45249353cc448984768949b0dc9a7f](url)
On page load if the field is required and value is already saved, then it should display green success indicator. 
Bug belongs to  "version": "6.0.0",

**Comment by SeanGroff** [comment]
> Loom: [https://www.loom.com/share/8d45249353cc448984768949b0dc9a7f](url) On page load if the field is required and value is already saved, then it should display green success indicator. Bug belongs to "version": "6.0.0",

The link for the Loom wouldn't work for me, but from what you just described, this is the expected behavior as of version 5.6.3

https://github.com/SelectQuoteLabs/SQForm/compare/v5.6.2...v5.6.3

**Comment by shahidmanzoorzekiexperts** [comment]
Here is a link it will work 
https://www.loom.com/share/8d45249353cc448984768949b0dc9a7f

However, we have been missing the functionality in  6.0.0.
