### ISSUE TITLE
Green Success Indicator on the Fields is missing. 

### ISSUE THREAD

**Issue by shahidmanzoorzekiexperts** [SelectQuoteLabs/SQForm#484]
When the conditions on a Field are initially Required, and then Fulfilled, and the form is SAVED (making it a Clean Form, again, with Saved and Valid Values), Green Success Indicator on the Fields is missing.
![image](https://user-images.githubusercontent.com/80986065/147968952-59e90f8f-eb91-4e49-bf22-901d98866f79.png)

Here is a link it will work
https://www.loom.com/share/8d45249353cc448984768949b0dc9a7f

However, we have been missing the functionality in 6.0.0.

**Comment by SeanGroff** [comment]
Hi @shahidmanzoorzekiexperts, as I mentioned in the last issue, this is working as expected.

Checkout the changelog https://github.com/SelectQuoteLabs/SQForm/blob/master/CHANGELOG.md#bug-fixes-1

5.6.3 (2021-10-08)
Bug Fixes
🐛 Only shows green fulfilled icon if field updated by user (a9747fb), closes #459

In version 5.6.3 the UI/UX team requested we change how the Green Success indicator works. The green success indicated should only appear if the user updates a field.

We no longer show the green success indicator on the initial page load for fields that are initially fulfilled.
