### ISSUE TITLE
Add a new Prop in SQFormGuidedWorkflow to style container/Section of SQFormGuidedWorkflow 

### ISSUE THREAD

**Issue by shahidmanzoorzekiexperts** [SelectQuoteLabs/SQForm#485]
We need to pass a dynamic style to the container of SQFormGuidedWorkflow.  currently we have <Section style={{padding: '20px'}}>
Which is fixed to 20px. In senior, we need a dynamic padding in our scenario we need it to 0px.
That's why we need a style prop here.

**Comment by 20BBrown14** [comment]
Closed with #492
