### ISSUE TITLE
SQFormDatePicker test fails randomly

### ISSUE THREAD

**Issue by SeanGroff** [SelectQuoteLabs/SQForm#486]
FAIL stories/__tests__/SQFormDatePicker.stories.test.js
  ● SQFormDatePicker Tests › should display new date after selecting from the calendar

    expect(element).toHaveValue(1/01/2022)

    Expected the element to have value:
      1/01/2022
    Received:
      01/01/2022

      103 |
      104 |     const testDate = getTestDay();
    > 105 |     expect(textField).toHaveValue(testDate);
          |                       ^
      106 |   });
      107 |
      108 |   it('should show as disabled when isDisabled is true', () => {

      at Object.<anonymous> (stories/__tests__/SQFormDatePicker.stories.test.js:105:23)

**Comment by 20BBrown14** [comment]
I don't think it's failing randomly, it's just that the field expects a leading zero on the month and day if they're less than 10. We originally wrote the test in October (ty git blame) so we never encountered it. I've updated the test on the Typescript branch. https://github.com/SelectQuoteLabs/SQForm/commit/010d7c3f95cb29e987950ce9fbb14143d2ad5b6a#diff-1bab2ed0ba8c4781616230d461311a4ba1acdfc5baba8363d7c5cf95c90e1dd0R101-R104

**Comment by SeanGroff** [comment]
@20BBrown14 Yep. Boyle also looked into this issue. We paired to fix this test on `master`.
We'll copy/pasta your logic (exactly, ours was similar) since the TypeScript branch will be the new `master` in the near future!

Linking this issue to Boyle's PR so this issue will close once Boyle's PR is merged
