### ISSUE TITLE
Icon Submit button not submitting the form. 

### ISSUE THREAD

**Issue by sqwaheed** [SelectQuoteLabs/SQForm#488]
Everything in loom.
Loom: https://www.loom.com/share/3097b3b049d94ea2b0753549cc4bbcff

SQForm Version: 5.8.0
scplus-shared-components: 5.4.2

**Comment by SeanGroff** [comment]
@sqwaheed Submit is spelled wrong for the button `type`

![Screen Shot 2022-01-04 at 9 44 01 AM](https://user-images.githubusercontent.com/4367312/148085051-82fca6d4-c78d-44e6-9ba2-6e0616b5efa9.png)

![Screen Shot 2022-01-04 at 9 44 22 AM](https://user-images.githubusercontent.com/4367312/148085058-078f5eb7-bf1f-448f-8e90-b9bef5dc70e9.png)

**Comment by sqwaheed** [comment]
Here is another Loom:
Still facing the same issue
https://www.loom.com/share/807ef64c1cd44e99813efc8b3a391944
