### ISSUE TITLE
Our TS type imports should use `import type`

### ISSUE THREAD

**Issue by 20BBrown14** [SelectQuoteLabs/SQForm#494]
While in the process of converting this library to TS we found that `import type` exists (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html). We should update all instances of importing a type to use `import type` and then continue to use while converting and developing the TS library.

related: #244

**Comment by SeanGroff** [comment]
Haha I was just typing this issue our myself. Thanks for adding this!
