### ISSUE TITLE
SQFormDatePickerWithCalendarInputOnly Errors when Date is Picked

### ISSUE THREAD

**Issue by aharpt** [SelectQuoteLabs/SQForm#511]
The SQFormDatePickerWithCalendarInputOnly Errors when a date is picked with the error message "Cannot read properties of undefined (reading type)".  Please see the attached loom for more details

https://www.loom.com/share/99b5cd3b3a4540cbb80c507119d05e43

**Comment by 20BBrown14** [comment]
I did some investigating. Hopefully this will give someone a jumping off point to investigate. I'll take another look here when i get done with some of my other in-progress work. https://www.loom.com/share/f6b0c3eda32646eb852de98d12d869cf
