### ISSUE TITLE
SQForInclusionList / SQForInclusionListItem

### ISSUE THREAD

**Issue by jamesgriffith9519** [SelectQuoteLabs/SQForm#568]
Currently, Sc3 admin has a new need/ask for some of the UX elements in our inclusion list to be enhanced/adjusted, these lists are currently consuming our SQFormInclusionList and SQFormInclusionListItem components, which render our FieldArray and checkboxes. I believe the current functionality is limited to singular form fields, being each individual checkbox. 

I believe the new ask would require an enhancement to one or both of these components so that you could have multiple form inputs representing one inclusion list item. 

I've attached the UX mock up a screenshot for some additional context: 
![Screen Shot 2022-01-18 at 11 54 09 AM](https://user-images.githubusercontent.com/60230956/149992698-2b6e9f4a-2721-49c9-ac7e-fcfac95935b7.png)

**Comment by jamesgriffith9519** [comment]
> Hm. Not sure what the ask is here. I think you're hoping that we could have an array of objects like
> 
> ```
> const formValues = {
>   inclusionListValue: [
>     { isChecked: true, otherValue: 'red' },
>     { isChecked: false, otherValue: 'green' }
>   ]
> }
> ```
> 
> Where `ischecked` is the checkbox and `otherValue` is the dropdown in your mock ups?
> 
> I just want to make sure that's what you're trying to get at with your issue, here. If not could you explain a little more in detail what you might expect the form field values to be?

yes that is spot on with what i think we are looking for

**Comment by 20BBrown14** [comment]
Gotcha. So I think trying to come up with a solution that does this would overengineer these components and make them harder to use and less applicable overall in some use cases. I feel like accomplishing something like this should rely on the consumer.

For instance, in your mock up. You could have the inclusion list with the checkboxes like normal and render a dropdown. You're likely creating those checkboxes on the fly based on some network requests. When you know what you need to render in the inclusion list you could update the initialValues to include a dropdown value for each checkbox and be dynamically named. So if your inclusionList field value is named "inclusionList" (for simplicity) and you have possible values "Jack, Prachi, Sean, and Harold" you could name each dropdown for the corresponding checkbox as "Jack_Color".

Then in your submit handler when you get the values you check 'is Jack checked? if so, check the "jack_color" field to get his favorite color and add it to the request or whatever.

This is my initial gut reaction to resolve something like this. Although, i haven't looked at how an enhancement like you've mentioned would play out yet. I'm definitely interested in discovering that, though, as well as other people's opinions on this.

**Comment by jamesgriffith9519** [comment]
Closing this as we were able to accomplish the task using Formiks dot notation pattern without needing any kind of adjustments/refactors to these components. 

Thanks @20BBrown14 for the great advice above!
