### ISSUE TITLE
SQForm submit button disabled with valid initial values

### ISSUE THREAD

**Issue by 20BBrown14** [SelectQuoteLabs/SQForm#59]
When using SQForm, the submit button is disabled even when the initial values provided to the form are valid values that satisfy the supplied validation schema. I believe this is because the form isn't dirty which is one of the requirements to enable the submit button and allow the form to be submitted.

See loom video: https://www.loom.com/share/cd911ae685f74441a53fc472cf5d441e

This is causing odd and semi-blocked behavior on LHAQT.

**Comment by Chris-Boyle** [comment]
Affected components: SQform, SQFormDialog, and SQFormDialogStepper

**Comment by 20BBrown14** [comment]
So the state of the SQForm button is controlled by [useFormButton](https://github.com/SelectQuoteLabs/SQForm/blob/master/src/components/SQForm/useFormButton.js#L4).

I think if we removed the [checks](https://github.com/SelectQuoteLabs/SQForm/blob/master/src/components/SQForm/useFormButton.js#L11) for [`dirty`](https://github.com/SelectQuoteLabs/SQForm/blob/master/src/components/SQForm/useFormButton.js#L15) the form will still work the way we want with the added benefit of having the "submit" button enabled in scenario described above.

Thoughts?

**Comment by SeanGroff** [comment]
@20BBrown14 Precisely.

https://github.com/SelectQuoteLabs/SQForm/pull/76#pullrequestreview-569654374

The real leg work is smoke testing all of the forms in our storybook stories to ensure this doesn't cause a new edge case.

**Comment by SeanGroff** [comment]
Working on this issue now that should close a few reported issues.
* Don't rely on `isTouched` for `isRequired` and `isFulfilled` states
* Same for `isDisabled` state for `useFormButton`
* Provide non-default option to disable Form button if no updates to the form have occurred
