### ISSUE TITLE
SQForm Autocomplete issue - add onInputChange prop

### ISSUE THREAD

**Issue by umerjamal100** [SelectQuoteLabs/SQForm#65]
We need to use `onChange` for `SQFormAutocomplete` to get SmartyStreets addresses but it is not fired when we type or update, it is being fired when we select the option, while it is working fine for `SQFormTextField`.
The current functionality is that we have to select an option to trigger that. 

Suggestion:
We need to implement `onInputChange` in our component, currently, we have `onChange` implemented only.

Please refer to the attached video for further details.
[loom video related to issue](https://www.loom.com/share/ab1dd9b80628461098b6aba5dd70372b)

**Comment by Chris-Boyle** [comment]
I can start looking at this.
