### ISSUE TITLE
Setting minimum Width for Dialog

### ISSUE THREAD

**Issue by AamirMaan** [SelectQuoteLabs/SQForm#66]
I am trying to set minimum width for Dialog, I tried using maxWidth prop which obviously didn't work as we don't have fullWidth for Dialog set to true, so is there any way around for setting a minimum width? If not, I think we should set fullWidth to true for Dialog, so we can control the size of dialog using maxWidth prop.
![image](https://user-images.githubusercontent.com/16385157/104359468-8222a880-5531-11eb-8d8d-abf2cbfab85e.png)

**Comment by SeanGroff** [comment]
@AamirMaan Thanks for opening this discussion.

What about declaring a minimum width in the body of the Dialog?

Something like

```jsx
<Dialog>
  <div style={{minWidth: '320px'}}>{contentGoesHere}</div>
</Dialog>
```

**Comment by AamirMaan** [comment]
@SeanGroff I think that will work fine, however, I think it will be convenient to control the width of dialog using maxWidth and have default value for fullWidth set to false. 
```
<Dialog maxWidth="200">
  <div style={{minWidth: '320px'}}>{contentGoesHere}</div>
</Dialog>
```

**Comment by SeanGroff** [comment]
@AamirMaan Thank you for the feedback. I'll keep this issue open so we can perform some discovery on this.
