### ISSUE TITLE
SQFormDialogStepper expose a way to reset/clear a steps values

### ISSUE THREAD

**Issue by Chris-Boyle** [SelectQuoteLabs/SQForm#69]
Currently in the SQForm we have the `SQFormResetButtonWithConfirmation` that will reset all of the forms values.  We need to have a way to do something similar to that in the stepper.  We can not use the SQFormResetButtonWithConfirmation component because it will reset all steps values and not just the current step.  If we want to give the ability to reset the current steps values should there be a button in the footer or just a function that we call that is triggered by a consumer adding something like a TextButton to the body of the step?

**Comment by umerjamal100** [comment]
Also using `SQFormResetButtonWithConfirmation` it just reset values to `initialValues`, if there is already a value present, it will reset to it, like in current loom we have ` address1: 'test'` in `initialValues` so on clicking reset  ` address1` is always set to test but we want it that address is cleared it should not have previous values it should empty the fields.
[loom](https://www.loom.com/share/bdd7fcd60ec248c2a50a16ac141a9d08)

**Comment by Chris-Boyle** [comment]
@umerjamal100 for this I think we need to expose a way to get just this steps values.  Then a way to reset just the values in the current step.  We can add a button on the consumer side that calls that function.

**Comment by umerjamal100** [comment]
We can solve this issue, by using `resetForm` method and we can pass props containing `newInitialValues` as an object containing new values, whenever we want to clean the initial Values of form or place custom values in it. I Will use a textButton for it and it will be placed in the header like this. Here are the useful links, please let me know if any suggestions.


![https://user-images.githubusercontent.com/18453833/105382874-5c348c80-5c32-11eb-9567-ecbd260dd938.png](https://user-images.githubusercontent.com/18453833/105382874-5c348c80-5c32-11eb-9567-ecbd260dd938.png)

[https://formik.org/docs/api/formik#resetform-nextstate-partialformikstatevalues--void](https://formik.org/docs/api/formik#resetform-nextstate-partialformikstatevalues--void)
![https://user-images.githubusercontent.com/18453833/105382075-86d21580-5c31-11eb-9fa2-3d9f0f02071e.png](https://user-images.githubusercontent.com/18453833/105382075-86d21580-5c31-11eb-9fa2-3d9f0f02071e.png)

**Comment by SeanGroff** [comment]
@umerjamal100 Absolutely.

I touch on this here https://github.com/SelectQuoteLabs/SQForm/issues/78#issuecomment-762993922
