### ISSUE TITLE
SQFormDialogStepper, SQFormDialog add loading state the dialogs

### ISSUE THREAD

**Issue by Chris-Boyle** [SelectQuoteLabs/SQForm#70]
In our dialogs we are not currently handling loading state.  There are times when we open the dialog and are not ready to render the components.  In this scenario we should show a loading spinner until the consumer says it is not loading anymore.  Currently a consumer can do this but it would make consumer code much cleaner to have the dialogs handle it.

I am proposing we show the Select Quote circles as a loading spinner.

**Comment by 20BBrown14** [comment]
> I am proposing we show the Select Quote circles as a loading spinner.

I suggest we allow the consumer to pass an optional loading component as well

**Comment by Chris-Boyle** [comment]
> > I am proposing we show the Select Quote circles as a loading spinner.
> 
> I suggest we allow the consumer to pass an optional loading component as well

I think we should probably solve for the 80% and just use our SelectQuote loading spinner for now until there is a request to allow consumers to define one.

**Comment by SeanGroff** [comment]
I can see this for the Stepper as it's more of an all in one solution.
I don't believe loading states are a concern of Dialogs though.

I think the first problem to solve is building a shared component that will take up 100% of the parent elements height and width. Then center the loading rings and below the rings an optional loading message. Then this styled loading component can be used anywhere without having to do something like

```jsx
<Dialog>
  {isLoading ? <div style={loadingStyle}><LoadingSpinner /></div> : content}
</Dialog>
```

instead it would be:

```jsx
{isLoading ? <LoadingSpinner /> : content}
```

Styling is already done for the consumer.
