### ISSUE TITLE
SQFormAutocomplete missing event in onInputChange

### ISSUE THREAD

**Issue by umerjamal100** [SelectQuoteLabs/SQForm#72]
We needed to add a handler in SQFormAutocomplete which will trigger on every keyPress, which was added but it is missing the event to return the entered value.

![image](https://user-images.githubusercontent.com/20329437/104609364-9ad1b200-5648-11eb-96e6-4f3ab1bdddac.png)
Shows that the event details is undefined when we try to access them
![image](https://user-images.githubusercontent.com/20329437/104609422-aa50fb00-5648-11eb-8f70-84d8c1edd7fb.png)

**Comment by SeanGroff** [comment]
Nice catch @umerjamal100 

https://github.com/SelectQuoteLabs/SQForm/blob/521a843070e75ec284d6bca57276e0c1ebe473d2/src/components/SQForm/SQFormAutocomplete.js#L147

`onInputChange` should be passed the event
