### ISSUE TITLE
SQFormDatePicker selecting same month/day in the future/past years is not acceptable

### ISSUE THREAD

**Issue by Chris-Boyle** [SelectQuoteLabs/SQForm#77]
When attempting to click the same date for a future year the calendar doesn't see anything as changed and doesn't want to close. 
**Steps to reproduce**
Open the datepicker 
Change the year to a future year
Select the same month/day for the future year

Loom in consumption: https://www.loom.com/share/7d37ad4b545347a4b6eba86475c12b61
Loom in Storybook: https://www.loom.com/share/d7452011fb52465aa6c4db73a4a98c39

**Comment by SeanGroff** [comment]
@Chris-Boyle Can you try passing this prop to SQFormDatePicker?
I'm curious if this works or not. I wouldn't consider this a solution to close this issue, but curious if this prop effects this.

```jsx
muiFieldProps={{
  allowSameDateSelection={true}
}}
```

**Comment by Chris-Boyle** [comment]
> @Chris-Boyle Can you try passing this prop to SQFormDatePicker?
> I'm curious if this works or not. I wouldn't consider this a solution to close this issue, but curious if this prop effects this.
> 
> ```js-jsx
> muiFieldProps={{
>   allowSameDateSelection: true
> }}
> ```
> 
> Edit: Correcting my pseudo code syntax

Just tested that in storybook and it looks like that will work!  Thanks.

**Comment by Chris-Boyle** [comment]
@SeanGroff  Should that be default to true?  It feels like that should always be true.  I can't see a scenario where we would not want to allow that.

**Comment by SeanGroff** [comment]
> @SeanGroff Should that be default to true? It feels like that should always be true. I can't see a scenario where we would not want to allow that.

@Chris-Boyle  Nah, this should default to false. 

To explain, by default if you open the date picker calendar and select Jan 18, 2021. The Calendar closes. If you open the date picker calendar again it won't let you select Jan 18, 2021, again.

My knee jerk reaction is this is a potential bug with the library itself. Where the library doesn't consider the same day but a different year a different day.

The next step we'll have to take is to see if this is a known issue with the library itself. https://next.material-ui-pickers.dev/api/DatePicker and sift through the GitHub issues.

**Comment by laurelbean** [comment]
Issue is over a year old. We can re-open a new one if this is found to still be an issue.
