### ISSUE TITLE
SQForm, SQFormDialog, SQFormDialogStepper should allow prop innerRef to be passed

### ISSUE THREAD

**Issue by 20BBrown14** [SelectQuoteLabs/SQForm#78]
Components that use Formik should allow for the prop `innerRef` to be passed through to Formik. Per the docs this will allow a consumer of SQForm to access certain formik context elements without requiring a subcomponent and/or wacky callback stuff.

The use case I need this for is to be able to access the values of the form in the component I use the form in so I can make decisions on what fields should be in the form on the fly.

Example usage:
```
const formRef = useRef();

const doSomething = () => {
  console.log(formRef.current.values);
}

return (
  <SQForm
    ...
    innerRef={formRef}
  >
  ...
</SQForm>
```

Formik docs: https://formik.org/docs/api/field#innerref
Affected components: SQForm, SQFormDialog, SQFormDialogStepper

**Comment by SeanGroff** [comment]
@20BBrown14  `useSQFormContext` will solve this challenge for you

**Comment by 20BBrown14** [comment]
@SeanGroff right, I would like an alternative to this, however. Consider the following:

I have a component where I am using SQForm. I want to display question two so long as the answer to question one is yes. I *could* use `onChange`, store the answer locally and display my second question based on that. But storing the answers in two places (Formik State, and local state) is a bad pattern I think. Instead, being able to access the form values directly in the same component I am using SQForm is better.

```
<SQForm ...>
  <QuestionOne />
  {answersToQuestionOneIsYes && <QuestionTwo />
</SQForm>
```

To use SQFormContext I have to do something like

```
const QuestionComponent = () => {
 const {values} = useSQFormContext()

  return (
    <QuestionOne />
    {values.questionOne && <QuestionTwo />
  )
}

<SQForm>
  <QuestionComponent /.>
</SQForm>
```

This is a valid solution but I feel like could be cumbersome and I am just making components for the sole purpose of using the SQFormContext hook that provide no other purpose or advantage. So I feel like if I could avoid that by doing something it'd be preferrable.

**Comment by SeanGroff** [comment]
Hrmmm....I'm not follow the need for innerRef based on the examples.

> But storing the answers in two places (Formik State, and local state) is a bad pattern I think

The state from `useSQFormContext` is the formik state. So we have one single source of truth. `useSQFormContext` is `useFormikContext` https://formik.org/docs/api/useFormikContext (just renamed)

`innerRef`isn't meant to grab formik values, it's to create a `ref` on the element if you need to do something imperatively in the DOM such as add autofocus or something. 

Example:

```jsx
const {values} = useSQFormContext()
const answersToQuestionOneIsYes = values.questionOne === 'yes';

return (
  <SQForm ...>
    <QuestionOne />
    {answersToQuestionOneIsYes && <QuestionTwo />
  </SQForm>
)
```

**Comment by 20BBrown14** [comment]
> innerRef isn't meant to grab Formik values, it's to create a ref on the element if you need to do something imperatively in the DOM

I suppose that's true. Looking at the [useFormikContext docs](https://formik.org/docs/api/useFormikContext#example) it looks it's okay to have a component that doesn't render anything but allows us to access the context and do things that we need to do. 

Although I'm not quite sure how that'd work in this case. Maybe I'm underthinking it? Also you're answer will not work. You can't use `useSQFormContext` (which calls `useFormikContext`) outside of a Formik component. See the docs here https://formik.org/docs/api/useFormikContext#useformikcontext-formikpropsvalues

```

const [answersToQuestionOneIsYes, setAnswersToQuestionOneIsYes] = React.useState('')

const UpdateFieldsToken = () => {
  const {values, setFieldValue} = useSQFormContext()
  setAnswersToQuestionOneIsYes(values.questionOne === 'yes');
  if (values.questionOne === 'no') {
    setFieldValue('questionTwo', ''); // Clear answer on questionTwo in Formik if we're not showing it
  }
}

return (
  <SQForm ...>
    <QuestionOne />
    {answersToQuestionOneIsYes && <QuestionTwo />
    <UpdateFieldsToken />
  </SQForm>
)
```

**Comment by SQshahjahan** [comment]
@SeanGroff Problem with this `const {values} = useSQFormContext()` it does not allow to use `useSQFormContext` unless current component is called inside the SQForm, it doesn't seems to find the context of form.

**Comment by SQshahjahan** [comment]
We might also need to access the `setFieldValue` along with `values` from `useSQFormContext`. 
`const {values, setFieldValue} = useSQFormContext();` this code doesn't work right now.

**Comment by SeanGroff** [comment]
I think we're trying to do too much in one component.

QuestionTwo.js
```jsx
function QuestionTwo() {
  const {values, setFieldValue} = useSQFormContext();
  
  React.useEffect(() => {
    if (values.questionOne === 'no') {
      setFieldValue('questionTwo', ''); // Clear answer on questionTwo in Formik if we're not showing it
    }
  }, [values.questionOne]);
  
  if (values.questionOne === 'no') {
    return null;
  }
  
  return <WhatEverField />
}
```

Questions.js
```jsx
function Questions() {
  return (
      <SQForm ...>
        <QuestionOne />
        <QuestionTwo />
  </SQForm>
  )
}
```

This is pseudo-code but hopefully, this is helpful

**Comment by 20BBrown14** [comment]
I'm not sure that's true. When there's two questions, as in our examples, you're right. But if we have 20 questions we have a component for each set of questions that are doing the exact same thing. Sure, we could make it reusable and pass it question names, question types (text, number, date, etc), when to display questions, etc etc but that is *a lot* of work. Not to mention it'd be hard to maintain and track down bugs.

Whereas, instead, if we had one function `clearUnusedQuestions` that is called when the form values change and another function `determineQuestionsToDisplay` that is called when form values change and does what their names imply. 

Although we're getting a little off topic for this particular issue. I do think this issue can be closed as innerRef isn't for this particular useCase.

**Comment by SeanGroff** [comment]
@20BBrown14 
Yea if we run into a form with 20 fields (Hopefully we can break that up into smaller forms grouped relationally) but IF not then we'd create a form field generator abstraction. Much like we already have to do for large FlexForm forms.

We pass in a config object then a Field is returned that renders based on conditions. 

`clearUnusedQuestions` would be part of the abstraction but it would be a useEffect to maintain a top-down data flow. The useEffect could call a function named clearUnusedQuestions.

Let's revisit if we run into the large form situation.

Closing this issue as innerRef is something we'd likely use inside the SQForm library code itself vs exposing it to the consumer.

**Comment by 20BBrown14** [comment]
> Let's revisit if we run into the large form situation.

hehe, I mentioned it because that's the situation I'm in right now

**Comment by SQshahjahan** [comment]
What I have done know, i have created another component `DisplayQuestions.js` and called that within the sqform context and got the `values and setFieldValue`, and that's kind of working. but as I am displaying 30 questions in `DisplayQuestions.js` I am wondering if I could reset the fields by using the `setFieldValue`.

**Comment by SeanGroff** [comment]
@20BBrown14 @SQshahjahan 

I'd highly recommend working with the project designer to see if the fields can be separated into smaller Forms that the user would fill out sequentially. 30 questions on the screen are bad for the end-user. This is also a pain for you as the developers. 

I don't have much context for the project to provide a great recommendation. Formik also has a `resetForm(nextState)` function if you need to reset form values in pass along the way. I don't know if this helps your situation but let's let the designers help us out.
