### ISSUE TITLE
info/help icon - Enhancement Request

### ISSUE THREAD

**Issue by caleboleary** [SelectQuoteLabs/SQForm#79]
It'd be nice to expose some prop `infoText` or `helpText`

if not undefined, show a small `i` icon (`@material-ui/icons/Info`) in the top right of a given form field, when hovered, show tooltip with infoText prop.

Could be useful to explain a given field whose purpose is not immediately obvious.

Thoughts?

**Comment by SeanGroff** [comment]
@caleboleary You might discuss this with Chris Nemeth and report back. Generally, he utilizes the Field Label for insight.
Certainly open to enhancements to help provide context into the field's purpose if the design details are approved by the design team.

**Comment by caleboleary** [comment]
Thanks Sean

Update per Nemeth
If you need field specific, long explanations, use the SectionHeader with Action Button to add a button on the top right that says something along the lines of 'info' - have it show information (via tooltip, modal, accordion) that you want to show. We don't want to show these 'what is this' descriptions to users every time, it should be findable but not in your face.
