### ISSUE TITLE
Add eslint plugin for Storybook

### ISSUE THREAD

**Issue by laurelbean** [SelectQuoteLabs/SQForm#850]
Right now our stories files are being flagged by eslint as warnings even though the stories are set up the way Storybook suggests. Using the eslint plugin for Storybook should solve this as well as assist with future stores file work.

Reference to get started: https://storybook.js.org/blog/how-to-use-storybook-with-eslint/

**Comment by 20BBrown14** [comment]
Part of the resolution for this issue should include changing the `npm run` lint command to includes the `./stories` directory. 
`eslint --ext .js,.ts,.tsx {./src,./stories} --max-warnings 0`
