### ISSUE TITLE
The "required" fields are not appearing as orange, and are greyed out instead

### ISSUE THREAD

**Issue by rizwanahmedziai** [SelectQuoteLabs/SQForm#86]
The "required" fields are not appearing as orange, and are greyed out instead. In the old Modals they used to be orange for required fields when not filled. In the current modal they only turn orange on blur.

![image-2021-01-27-16-21-34-921](https://user-images.githubusercontent.com/41960965/106619735-b585af80-6592-11eb-9f1b-3ba4c99ad7a1.png)

https://www.loom.com/share/af71cd61b72348ce85744bae35cbf73c

**Comment by lucas-homer** [comment]
this is not really a bug, it's a fundamental pattern in formik -- https://formik.org/docs/tutorial#visited-fields

**Comment by rizwanahmedziai** [comment]
Thank you for that link @lucas-homer and you are right its not really a bug and that is what I thought initially and reported as such on the bug ticket related to this issue on our repo. But I was asked to report this and hopefully get it to work in that particular way as mentioned above where the 'required' gets highlighted in orange for required fields, regardless of whether the user has visited it or not.

**Comment by lucas-homer** [comment]
I don't know what else to say other than whoever wrote that quote needs to understand that SQForm behaves slightly differently in this regard, and it's a design supported by industry leaders.

**Comment by rizwanahmedziai** [comment]
@lucas-homer

I noticed that we are passing validateOnMount={true} in the SQForm but that fix was made in formik v2.16. Please see the link below: 

https://codesandbox.io/s/formik-codesandbox-template-forked-mz9le?file=/index.js

So, I believe this issue can resolved (or at least the functionality we are looking for in LQT can be achieved)  if we bump up the Formik version to 2.16 or above as opposed to the current 2.14.

**Comment by SeanGroff** [comment]
Hi @rizwanahmedziai

Can you provide some further information on this request, please?
Who is requesting this change? What is the link to the ticket?
I'd like to discover who to have this conversation with.

Thanks!

**Comment by rizwanahmedziai** [comment]
@SeanGroff Sure mate. Here is the link to the ticket: 
https://selectquote.atlassian.net/browse/P12-1915
You can discuss this further with Stuart Washington or Skylar Hoch

**Comment by rizwanahmedziai** [comment]
Link to the same issue on Formik
https://github.com/formium/formik/issues/2652

**Comment by SeanGroff** [comment]
@rizwanahmedziai I've moved the discussion back to the Jira ticket
https://selectquote.atlassian.net/browse/P12-1915?focusedCommentId=174382
I'll revisit this once UI/UX chimes in

**Comment by SeanGroff** [comment]
Closing this issue per https://selectquote.atlassian.net/browse/P12-1915?focusedCommentId=174404

**Comment by rizwanahmedziai** [comment]
Thank you for the input @SeanGroff That removed our confusion.
