### ISSUE TITLE
SQForms: Dropdown - Update component

### ISSUE THREAD

**Issue by asim-sqfe** [SelectQuoteLabs/SQForm#864]
Update the current implementation of the Dropdown with added specifications. Here is the current implementation of this SQForm: https://master--5f4431386ea00a00220d495c.chromatic.com/?path=/story/components-sqformdropdown--default (this is an example link)

Design reference: https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=1518%3A11678 
Typography: https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=340%3A9946 
Color: https://www.figma.com/file/DsJr2cFZqMYkOX6VjcuhqW/SC3-DESIGN-SYSTEM?node-id=340%3A9646 

Default:
Label:  Text Style: Label 12 px Weight: 400
Value: Text Style: Value 14px Weight: 600 Semi-bold

Focused:
Label: Text Style: Label 12 px Weight: 400
Value: Text Style: Value 14px Weight: 600 Semi-bold

With Validation:
Label: Text Style: Label 12 px Weight: 400
Value: Text Style: Value 14px Weight: 600 Semi-bold
Line: #C67000 Warning 
Helper Text/icon: #C67000 Warning   #3C7107 Text/Success 
Icon Size: 12 x 11 Warning  9 x 11 Success badge

**Comment by laurelbean** [comment]
Completed in PR #867
