### ISSUE TITLE
SQFormDatePicker Tests Update

### ISSUE THREAD

**Issue by aharpt** [SelectQuoteLabs/SQForm#876]

**Comment by aharpt** [comment]
@laurelbean I have made a few adjustments, but just curious if you had anything specific in mind in terms of things you wanted to see changed on the DatePicker tests?

**Comment by laurelbean** [comment]
There were a few test cases I couldn't get to work because for some reason Testing Library was interpreting the text box as a button. See my comment here: https://github.com/SelectQuoteLabs/SQForm/issues/265#issuecomment-880045256
