### ISSUE TITLE
SQFormDialog content body margin

### ISSUE THREAD

**Issue by SeanGroff** [SelectQuoteLabs/SQForm#88]
The SQDialog Modal needs specific interior margins set by default.
Interior Content Margins of the scrollable content area needs to be `20PX` on the top, left, bottom, and right sides of the content area.

UPDATE: As of 6/21/2021, Nemeth has clarified we should change the existing `padding: 16px 24px` of the `DialogContent` component to be `padding: 20px` (20 pixels of padding for the Top, Left, Bottom, and Right)

This should be a BREAKING change as consumers who previously added a `div` to control the padding will need to fix their existing implementation.

Comp: https://www.sketch.com/s/b1684560-808a-4f20-960d-fd3969080240/a/GmoOLYY#Inspector

**Comment by 20BBrown14** [comment]
Looking at this it seems that the content already has margins for the "scrollable" area. Or perhaps I'm missing something? Screenshots below from storybook. Although not of the same size asked for here.

<img width="1078" alt="Screen Shot 2021-02-26 at 11 02 19 AM" src="https://user-images.githubusercontent.com/29528409/109331220-33e81100-7822-11eb-8d07-2c1e84c78139.png">
<img width="1065" alt="Screen Shot 2021-02-26 at 11 02 13 AM" src="https://user-images.githubusercontent.com/29528409/109331223-35b1d480-7822-11eb-9061-bc8056b252cd.png">
<img width="1064" alt="Screen Shot 2021-02-26 at 11 01 33 AM" src="https://user-images.githubusercontent.com/29528409/109331224-35b1d480-7822-11eb-9f7d-739aa35b69a6.png">
<img width="1075" alt="Screen Shot 2021-02-26 at 11 01 27 AM" src="https://user-images.githubusercontent.com/29528409/109331225-35b1d480-7822-11eb-9fa8-48e30fe21af5.png">

**Comment by Chris-Boyle** [comment]
The current padding is 8px, 24px
![image](https://user-images.githubusercontent.com/20329437/122820645-733edf80-d2a1-11eb-8004-56f532a05159.png)
I will set a padding style on the DialogContent to have the padding be 20px on all sides
          <DialogContent style={{overflowY: 'visible', padding: '20px'}}>
